import pyautogui

SCREEN_WIDTH, SCREEN_HEIGHT = pyautogui.size()
PIXEL_WIDTH, PIXEL_HEIGHT = pyautogui.screenshot().size
SCALER = PIXEL_HEIGHT / SCREEN_HEIGHT

APP_WIDTH, APP_HEIGHT = 450, 720
APP_PIXEL_WIDTH, APP_PIXEL_HEIGHT = int(APP_WIDTH * SCALER), int(APP_HEIGHT * SCALER)

MIN_REFRESH_INTERVAL = 0.2

SCREEN_SAMPLE_RATE = 1